### ISSUE TITLE
moving to OCA

### ISSUE THREAD

**Issue by eLBati** [Yenthe666/auto_backup#11]
Dear @Yenthe666 
we would like to include your module ```auto_backup``` in OCA repo
https://github.com/OCA/server-tools
What do you think?

**Comment by Yenthe666** [comment]
Dear @eLBati 

It would be great to see my module added to the OCA repo! :+1: I think its best to start from the master version I have, since this also includes changing the port, which isn't in the 8.0 version.
Not all of the code is 100% by the Odoo guideline rules though, so I assume this should be fixed?
How should we go from here?

**Comment by Yenthe666** [comment]
@eLBati any update on this?

**Comment by archetipo** [comment]
Dear @Yenthe666 
  here: https://github.com/OCA/server-tools/pull/203 the PR for including your module in OCA/server-tools.

**Comment by Yenthe666** [comment]
Thanks @archetipo! I'll close this issue here. Feel free to post if you have any questions or something!
