### ISSUE TITLE
Backups stuck in loop

### ISSUE THREAD

**Issue by zozolpl** [Yenthe666/auto_backup#148]
Hello, autobackup worked good for long time, but few days ago I noticed that 100% of disk is used - backups should be generated every 12h but when script starts it is making copies until disk is full. 
Error log is empty. 
If I delete all copies and turn on scheduled actions it will wait untul next scheduled run, then it stucks in loop. 
I noticed problem with other scheduled actions for example mails are not sending properly or abbandoned carts are not showing in website orders. 
Repeat missed unchecked. 
Odoo v12 Ubuntu 18. 

// Time betwen copies is about 120/150secs, I raised timeout to 400sec didnt fix

**Comment by zozolpl** [comment]
ERROR ? odoo.service.server: WorkerCron (2363) timeout after 120s
Where else is timeout? I raised in odoo.conf and odoo-server.conf

**Comment by Yenthe666** [comment]
It's the timeout in the odoo-server.conf file. The filling of your storage is probably because the cron is killed before it completes. While it is running it creates backups, it then gets killer through the timeout which kills the workers and stops the cron. The cron stops, is triggered again x time later and does the same vicious loop again resulting in your storage being filled.

The fix is probably rather easy:
1. Change the next execution date of the backup cron to a date in the future
2. Check off the option "Repeat missed".

**Comment by zozolpl** [comment]
Thanks for answer!
In odoo-server.conf I added Timeout = 400 
But still getting info about timeout after 120s

**Comment by Yenthe666** [comment]
Check https://www.odoo.com/documentation/13.0/setup/deploy.html for detailed deployment documentation
