### ISSUE TITLE
Odoo 13 - Error(s) with "E-mail to notify" functionality

### ISSUE THREAD

**Issue by spilymp** [Yenthe666/auto_backup#153]
Hello,
I am very thankful for the module and that everything is basically running smoothly. So thank you very much for the module! But I noticed that the "E-mail to notify" functionality does not work for me in Odoo 13.
If it's a configuration problem of my site, please let me know, otherwise here are the problems I noticed:

### 1. Can not find mailserver:
https://github.com/Yenthe666/auto_backup/blob/3621735aee8969b9b5f90585c75998ff4cb9338a/auto_backup/models/db_backup.py#L267

I have an outgoing mail server configured but if I debug and stop on this line I always get no object in return. Therefore no mail could be sent. My solution was to switch this line to the following:
`ir_mail_server = self.env['ir.mail_server'].search([], limit=1)`

### 2. Passwort in plain text
https://github.com/Yenthe666/auto_backup/blob/3621735aee8969b9b5f90585c75998ff4cb9338a/auto_backup/models/db_backup.py#L270-L271

Not really a problem or bug, but is it really reasonable to print the sftp password in plaintext in the e-mail?

### 3. Response e-mail address
https://github.com/Yenthe666/auto_backup/blob/3621735aee8969b9b5f90585c75998ff4cb9338a/auto_backup/models/db_backup.py#L273

The response e-mail address is build by the following scheme:

> auto_backup@[database_name].com

Even if probably no one ever answers these mails, shouldn't there at least be a meaningful/correct reply mail address in them? My personal adjustment for this looks as follows:

```python
catch_all_domain = self.env["ir.config_parameter"].sudo().get_param("mail.catchall.domain")
response_mail = "auto_backup@%s" % catch_all_domain if catch_all_domain else self.env.user.partner_id.email
msg = ir_mail_server.build_email(response_mail, [rec.email_to_notify],
(...)
```

### 4. Sending mails does not work
https://github.com/Yenthe666/auto_backup/blob/3621735aee8969b9b5f90585c75998ff4cb9338a/auto_backup/models/db_backup.py#L277

When I run this line, I get the following error message:
> {TypeError}'Cursor' object is not subscriptable

Apparently the function can no longer be called this way. My solution for this looks as follows:
```python
ir_mail_server.send_email(msg)
```

I hope that my problems can be solved and I am looking forward to hints and remarks!

**Comment by Yenthe666** [comment]
Hi @spilymp,

Thanks a lot for this very detailed bug report, it helps a lot. In fact you're pretty right too.
1) Indeed, we need a search and take the default one. I'd say we can do better in the search by taking the mail server with the lowest sequence (this is usually the most active/used one):
`ir_mail_server = self.env['ir.mail_server'].search([], order='sequence asc', limit=1)`
2. Yeah I've never been sure about this one honestly. Perhaps I should just put in some stars so the user has to check in Odoo or leave the password out?
3. Going to think about this one but you're probably right this isn't the best one now.
4. Indeed it doesn't, this is still a small leftover of the old API.

I've fixed 1 & 3 already in https://github.com/Yenthe666/auto_backup/commit/9557f4926039b8b5949e46b6b0723ec828111003 (I didn't test it since I'm low on time but this should work)

**Comment by spilymp** [comment]
Hi @Yenthe666,

many thanks for the quick resolution of problems 1 and 4! For 2 and 3 I opened a pull request #157 with my suggested changes. For problem 2 I simply replaced the password with stars. For problem 3 I included my idea, what would be your approach here?

**Comment by Yenthe666** [comment]
Thanks again for reporting and the PR! All things are handled now :)
